spring:
    profiles.active: default
    jmx.enabled: true
    datasource:
        source:
            name: store-rdbms-db-44-cdipp-trid
            url: jdbc:sqlserver://10.10.15.128:1433;databaseName=cdipp-trid;SendStringParametersAsUnicode=false
            username: cdippapp
            password: 123@@cdippapp
            driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
            platform: mssql
            initialization-mode: always
            continue-on-error: true
            jpa:
                hibernate.ddl-auto: none
                database-platform: org.hibernate.dialect.SQLServer2012Dialect
        destination:
            name: store-rdbms-local-cdipp-trid
            url: jdbc:sqlserver://192.168.56.2:1433;databaseName=CDIPP_DATA;SendStringParametersAsUnicode=false
            username: cdippapp
            password: admin
            driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa:
        generate-ddl: true
        hibernate.ddl-auto: none
        show-sql: true
        format-sql: true