spring:
    application:
        name: spring-data-jpa-multiple-datasource
    profiles:
        active: default
    data.jpa.repositories.enabled: true
    jpa:
        database-platform: POSTGRESQL
        generate-ddl: true
        open-in-view: true
        show-sql: false
        hibernate.ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL94Dialect
                default_schema: production
        
datasource:
    people:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://10.10.15.171:5432/people?currentSchema=production
        username: postgres
        password: postgres
        type: org.apache.tomcat.jdbc.pool.DataSource
        jmx-enabled: true
        initialSize: 2
        maxActive: 100
        maxIdle: 5
        minIdle: 2
        maxWait: 600000
        testOnBorrow: true
        validationQuery: select 1
        minEvictableIdleTimeMillis: 60000
        removeAbandoned: true
        removeAbandonedTimeout: 60000
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        
    office:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://10.10.15.171:5432/office?currentSchema=production
        username: postgres
        password: postgres
        type: org.apache.tomcat.jdbc.pool.DataSource
        jmx-enabled: true
        initialSize: 2
        maxActive: 100
        maxIdle: 5
        minIdle: 2
        maxWait: 600000
        testOnBorrow: true
        validationQuery: select 1
        minEvictableIdleTimeMillis: 60000
        removeAbandoned: true
        removeAbandonedTimeout: 60000
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        